variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates' 
    ApimPolicyRoot: '$(Build.SourcesDirectory)\Resources\ApimPolicies'
    PSScriptsRoot: '$(Build.SourcesDirectory)\Resources\PSScriptsRoot'
    HtmlContent: '$(Build.SourcesDirectory)\Resources\HtmlContent'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.3.0
    endpoint: 'GitHub (ESFA)'

jobs:

- job: BuildAndTestArmTemplate
  displayName: BuildAndTestArmTemplate
  pool:
    name: Continuous Integration 02 - SSD - 160ACU
    demands:
    - msbuild
    - visualstudio

  steps:
  - template: AzureDevOpsTemplates/Build/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: $(ArmTemplateRoot)

  - task: CopyFiles@2
    displayName: 'Copy APIM policies to staging'
    inputs:
      SourceFolder: $(ApimPolicyRoot)
      TargetFolder: $(build.artifactstagingdirectory)/Azure/ApimPolicies

  - task: CopyFiles@2
    displayName: 'Copy scripts to staging'
    inputs:
      SourceFolder: $(PSScriptsRoot)
      TargetFolder: $(build.artifactstagingdirectory)/PSScripts

  - task: CopyFiles@2
    displayName: 'Copy content files to staging'
    inputs:
      SourceFolder: $(HtmlContent)
      TargetFolder: $(build.artifactstagingdirectory)/Content

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: AzureResources